name: segmenteverygrain2

channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pyqt
  - pandas
  - jupyterlab
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - networkx
  - shapely
  - pip
  - pip:
    - pillow
    - rasterio
    - opencv-python
    - rtree
    - tensorflow
    - segment-anything
    - segmenteverygrain
  # - pytorch::pytorch  # Ensure PyTorch is installed from PyTorch channel
  # - pytorch::torchvision
  # - pytorch::torchaudio
